node:
  host: 127.0.0.1

server:
  port: 6767

gRPC:
  port: 8083

spring:
  data:
    mongodb:
      uri: ${mongodb.uri:@mongodb.uri@}
  redis:
    database: ${redis.db:@redis.db@}
    host: ${redis.host:@redis.host@}
    port: ${redis.port:@redis.port@}
    # password: 123456
    max-active: 10
    max-wait: 500
    max-idle: 5
    min-idle: 1
    timeout: 2000
