server:
  port: 8080
  servlet:
    application-display-name: skyblue


netty:
  tcp:
    port: 8081
  udp:
    port: 8082
  gRPC:
    port: 8083

curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: 127.0.0.1:2181
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 5000


spring:
  data:
    mongodb:
      uri: mongodb://10.40.7.18:27017/sas_multi_dev
